name: C++ CI

on:
  push:
    branches:
      - developer-3.0  # Runs when code is pushed to the developer branch
  pull_request:
    branches:
      - developer-3.0  # Runs for pull requests targeting the developer branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to allow for full git context

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake g++

      - name: Build project
        run: cmake -S . -B build && cmake --build build

      - name: Run tests
        working-directory: build
        run: ctest --verbose
